require "_settings"
require "_autocmd"
require "_mapping"
require "_theme"
require "_colorizer"
require "_lsp"
require "_completion"
require "_diagnostic"
require "_treesitter"
require "_telescope"
require "_devicons"
require "_status"
require "_tree"
require "_formatter"
require "_svelte"
-- require "_minimap"
